const types = {
    REGISTRATION_PROCESS_START: 'REGISTRATION_PROCESS_START',
    REGISTRATION_PROCESS_FINISHED: 'REGISTRATION_PROCESS_FINISHED',
    LOGIN_PROCESS_START: 'LOGIN_PROCESS_START',
    LOGIN_PROCESS_FINISHED: 'LOGIN_PROCESS_FINISHED',
  };
  
  export default types;
  