const types = {
    GET_BANNER_ALERT_START: 'GET_BANNER_ALERT_START',
    GET_BANNER_ALERT_FINISH: 'GET_BANNER_ALERT_FINISH',
    CLEAR_ONE_NOTIFICATION:'CLEAR_ONE_NOTIFICATION',  
    CLEAR_BANNER_ALERT:'CLEAR_BANNER_ALERT',
  };
  
  export default types;
  